[package]
name = "modbus_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1.34.0", features = ["rt", "rt-multi-thread", "time"]}
tokio-modbus = "*"
hex = "0.4.3"
